name: Bug report
description: Report something that isn't working correctly.
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened, and what did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps or topology file to trigger the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: motel version
      description: Output of `motel --version`.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. macOS 15.3, Ubuntu 24.04
    validations:
      required: false
